name: Build

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install packages, or cache.
        uses: actions/cache@v3
        id: cache
        with: |
          ${{ github.workspace }}/.choco/cache
        run: |
          choco install boost-msvc-14.3
        # uses: # choco install boost-msvc-14.3

      # - name: Build - Rust
      #   run: |
      #     cargo --version
      #     rustc --version
      #     cargo build --release
      
      - name: Build - CXX
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" -A Win32 -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . --config Release