name: Build

on: [push]

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1

      - name: Installing packages, and cache everything
        uses: johnwason/vcpkg-action@v3
        if: matrix.os == 'windows-latest'
        with:
          pkgs: boost-date-time boost-system openssl
          triplet: x86-windows-static

      # - uses: johnwason/vcpkg-action@v3
      #   runs-on: windows-latest
      #   with:
      #     pkgs: boost-date-time boost-system openssl
      #     triplet: x86-windows-static


      # - name: Build - Rust
      #   run: |
      #     cargo --version
      #     rustc --version
      #     cargo build --release
      
      - name: Build - CXX
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" -A Win32 -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . --config Release