name: Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Checkout SourceMod
        uses: actions/checkout@v3
        with:
          repository: alliedmodders/sourcemod
          submodules: recursive
          path: sourcemod
      - name: Checkout MetaMod
        uses: actions/checkout@v3
        with:
          repository: alliedmodders/metamod-source
          submodules: recursive
          path: metamod-source
      - name: Checkout CSGO SDK
        uses: actions/checkout@v3
        with:
          repository: alliedmodders/hl2sdk
          ref: csgo
          path: hl2sdk/csgo
      - name: Installing packages
        if: matrix.os == 'windows-latest'
        uses: johnwason/vcpkg-action@v3
        with:
          pkgs: boost openssl
          triplet: x86-windows-static
      - name: Win - Build
        if: matrix.os == 'windows-latest'
        run: |
          $env:HL2SDK_CSGO="$GITHUB_WORKSPACE\hl2sdk-csgo"
          $env:SOURCEMOD="$GITHUB_WORKSPACE\sourcemod"
          $env:METAMOD_SOURCE="$GITHUB_WORKSPACE\metamod-source"
          $CPUCore=$(Get-WmiObject -Class Win32_Processor | Select-Object -Property Name, Number*).NumberOfCores
          mkdir build; cd build
          cmake -G "Visual Studio 17 2022" -A Win32 -DCMAKE_BUILD_TYPE=Release -DTARGET_ARCH=x86 -DHL2SDK_ENGINE_NAME=csgo -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x86-windows-static ..
          cmake --build . --config Release
      
